#!/usr/bin/env bash
# Usage: generate emptyfile
# Summary: Create empty files into the empty directories
# Help: Create empty files into the empty directories
# Options:
#     -d  define the finding directory (default: .)
#     -f  define the empty file name (default: .gitkeep)

set -eu

. $(dirname $0)/../lib/bash/functions
. $(dirname $0)/../lib/bash/logger

: ${GENERATE_EMPTYFILE_FIND_DIR:="."}
: ${GENERATE_EMPTYFILE_FILE_NAME:=".gitkeep"}

while getopts d:f: OPT
do
    case $OPT in
        d)
            GENERATE_EMPTYFILE_FIND_DIR=$OPTARG
            ;;
        f)
            GENERATE_EMPTYFILE_FILE_NAME=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

while read
do
    [[ -z "$REPLY" ]] && continue
    logger.debug "Create: $REPLY/$GENERATE_EMPTYFILE_FILE_NAME"
    touch $GENERATE_EMPTYFILE_FIND_DIR/$REPLY/$GENERATE_EMPTYFILE_FILE_NAME
done <<EOS
$(find $GENERATE_EMPTYFILE_FIND_DIR -type d -name ".git" -prune -o -type d -empty -print)
EOS
