#!/usr/bin/env bash
# Usage: generate workdir
# Summary: Generate a work directory
# Help: Generate a work directory

set -eu

. $(dirname $0)/../lib/bash/functions
. $(dirname $0)/../lib/bash/logger

: ${WORK_PARENT_PATH:="$HOME/Dropbox/Notes"}
DIR_NAME=$(date +%Y%m%d%H%M%S)
DIR_PATH="$WORK_PARENT_PATH/$DIR_NAME"

if [ -e $DIR_PATH ]; then
    logger.error "$DIR_PATH already exists."
    exit false
fi

mkdir -p $DIR_PATH
logger.info "Created \"$DIR_PATH\""
