#!/usr/bin/env bash

set -eu

. $(dirname $0)/../lib/bash/functions
. $(dirname $0)/../lib/bash/logger

REPOSITORY_ROOT=$(realpath $(dirname $0)/..)

while read; do
    [[ -z "$REPLY" ]] && continue
    file_name=$(basename $REPLY)
    logger.debug "Create symlink: $file_name"
    ln -sf $REPOSITORY_ROOT/{,.git/}hooks/$file_name
done <<EOS
$(find $REPOSITORY_ROOT/hooks -type f -print)
EOS
