#!/usr/bin/env bash

array.contains () {
  local e
  for e in "${@:2}"; do [ "$e" == "$1" ] && return 0; done
  return 1
}

date_lesseq() {
  local dt1, dt2
  dt1=$(date -d "$1" '+%s')
  dt2=$(date -d "$2" '+%s')
  [ $dt1 -gt $dt2 ] && return 1
  return 0
}

date_lessthan() {
  local dt1, dt2
  dt1=$(date -d "$1" '+%s')
  dt2=$(date -d "$2" '+%s')
  [ $dt1 -lt $dt2 ] && return 0
  return 1
}

err.trap() {
  local errcode=$?
  echo "error line $1: command exited with status $errcode."
}

trap 'err.trap $LINENO' ERR
